### ISSUE TITLE
"ue4 root" throws "NameError" on Mac OS X

### ISSUE THREAD

**Issue by sleeptightAnsiC** [adamrehn/ue4cli#57]
Hello,

using "ue4 root" on Mac OS X will always throw the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/ue4", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ue4cli/cli.py", line 222, in main
    SUPPORTED_COMMANDS[command]['action'](manager, args)
  File "/usr/local/lib/python3.11/site-packages/ue4cli/cli.py", line 36, in <lambda>
    'action': lambda m, args: print(m.getEngineRoot()),
                                    ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ue4cli/UnrealManagerBase.py", line 60, in getEngineRoot
    self._engineRoot = self._getEngineRoot()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ue4cli/UnrealManagerBase.py", line 620, in _getEngineRoot
    return self._detectEngineRoot()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ue4cli/UnrealManagerDarwin.py", line 25, in _detectEngineRoot
    if version < parse_version('5.0.0'):
       ^^^^^^^
NameError: name 'version' is not defined
```

This is happening because "version" is actually not assigned anywhere in [UnrealManagerDarwin._detectEngineRoot](https://github.com/adamrehn/ue4cli/blob/master/ue4cli/UnrealManagerDarwin.py#L25), even simple LSP catches this:

![Screenshot 2024-01-23 at 14 56 55](https://github.com/adamrehn/ue4cli/assets/91839286/b1b2a900-5db7-4bfc-a53a-5175fd4ceebe)

On my side, adding `version = parse_version(self.getEngineVersion())` on line before simply fixes this.

**Comment by sleeptightAnsiC** [comment]
Looking through pull requests, someone already encountered this issue: https://github.com/adamrehn/ue4cli/pull/50

**Comment by sleeptightAnsiC** [comment]
https://github.com/sleeptightAnsiC/ue4cli/commit/cc4773751032623f38cdda12e252a593db909efd
should fix it

**Comment by sleeptightAnsiC** [comment]
Ahhh, nvm, there is another bug here, my fix would only cause make it work for few function calls and then the recursion would occur causing https://github.com/adamrehn/ue4cli/issues/47
