### ISSUE TITLE
'__main__.py' isn't used anywhere

### ISSUE THREAD

**Issue by sleeptightAnsiC** [adamrehn/ue4cli#69]
`__main__.py` does not seem to be used anywhere.
The entry point for ue4cli is actually in a different place:
https://github.com/adamrehn/ue4cli/blob/fed71c1af4cffe3fed9358b08430068ad9454b77/setup.py#L35-L37

I'm also not able to use this file directly like a script, as it does not bootstrap the module:
```bash
# cwd is repo root directory
$ python ./ue4cli                
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/kornel/Projects/ue4cli/./ue4cli/__main__.py", line 1, in <module>
    from .cli import main
ImportError: attempted relative import with no known parent package
```
Maybe I'm not using it right?
Shall we fix this?

**Comment by sleeptightAnsiC** [comment]
NOTE:
To be able to use ue4cli from sourcecode without installing it, one must move the `__main__.py` file to the ue4cli's root directory and change `from .cli import main` to `from ue4cli.cli import main`. Then invoking the scripts will be possible by `python /path/to/ue4cliroot`

ref: https://www.geeksforgeeks.org/usage-of-__main__-py-in-python/

Still not sure about the lines from `setup.py`, but we probably can leave it as it is.
